### ISSUE TITLE
Ao enviar dados JSON com aspas simples ao invés de aspas duplas, causa erro

### ISSUE THREAD

**Issue by rafaelclp** [uiansol/lol-counter#12]
{'tip': 'test tip'} causa erro no json.loads. Esse método inútil só aceita aspas duplas -.-!!

E a suite de testes do tornado envia o json com aspas simples... o servidor deveria aceitar os dois, ambos são válidos!!

**Comment by rafaelclp** [comment]
Corrigido. Usando ast.literal_eval("string com literal") ao invés de json.loads. Façam o mesmo!

**Comment by v-silva** [comment]
Encontrei esse comportamento, pesquisei um pouco e concluí que JSON era assim mesmo. Talvez o uso por aí aceite aspas simples (e o fix é bem vindo), mas não é o que http://www.json.org/ diz...

**Comment by rafaelclp** [comment]
Verdade. De qualquer forma, nós vamos aceitar. Javascript e Python aceitam, não vou causar Bad Request numa requisição por besteira. Acho que a gente não perde nada deixando o servidor tolerante nesse sentido.
