### ISSUE TITLE
PATCH causando 404 Not Found

### ISSUE THREAD

**Issue by rafaelclp** [uiansol/lol-counter#6]
Os métodos de PATCH para /tip e /counter estão dando Not Found.

Testado para:
PATH /api/champion/1/tip/35
Dados: { action: "voteUp" }

**Comment by v-silva** [comment]
Eles ainda nao foram implementados! Deixei edicoes (patch e delete) para a proxima sprint ja que ainda nao temos login...

**Comment by rafaelclp** [comment]
Ah certo, faz sentido...

De qualquer forma, já implementei no cliente os métodos na interface REST.
