### ISSUE TITLE
Abas para sugestoes

### ISSUE THREAD

**Issue by victorssilva** [uiansol/lol-counter#8]
Acredito que o app ficaria bem mais moderno se tivessemos abas para as 3 opcoes de sugestoes ao inves de botoes.

**Comment by rafaelclp** [comment]
Apenas complementando, Alysson reclamou de:

"Os submenus de Champion, Runes e Itens devem aparecer e desaparecer quase instantaneamente ao clicarmos em cima do nome Champios, Runes ou Itens?"

Acredito que ao mudar para abas já resolve o problema, mas se não mudar, corrige isso ao menos.

**Comment by rafaelclp** [comment]
Foi implementado o sistema de carrossel por Tércio, ao invés de abas (já que o texto ficava muito apertado). Issue resolvida.
